apiVersion: apps/v1
kind: Deployment
metadata:
  name: astonvilla-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: astonvilla-app
  template:
    metadata:
      labels:
        app: astonvilla-app
    spec:
      containers:
      - name: astonvilla-app
        image: m2l2k/astonvilla:1.1.69
        ports:
        - containerPort: 80
